### ISSUE TITLE
Routes pages not working properly

### ISSUE THREAD

**Issue by drtrppr** [cakephp/cakephp.org#253]
In routes.php there's for example:

`$routes->connect('/newsletter', ['controller' => 'Pages', 'action' => 'display', 'newsletter']);`

The url stays 'https://cakephp.org/pages/newsletter', instead of the intended  'https://cakephp.org/newsletter' 

Very interested in solution, [since I'm experiencing same problem](https://discourse.cakephp.org/t/pagescontroller-routes-cakephp-4/9759/3) on my website.

**Comment by LordSimal** [comment]
It works exactly as it is configured.
```
$routes->connect('/newsletter', ['controller' => 'Pages', 'action' => 'display', 'newsletter']);
```
only says that the URL `/newsletter` will show the Newsletter page.

But there is also this part of the routes config:
```
$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
```

Since the Newsletter page is just simple page it can also be access via that route `/pages/newsletter`

But thats only one part of the puzzle.

E.g. the footer newsletter link is `/pages/newsletter` because of the order how the routes are configured.
If you put 
```
$routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
```
bellow 
```
$routes->connect('/newsletter', ['controller' => 'Pages', 'action' => 'display', 'newsletter']);
```
it will also link "correctly" to `/newsletter` because links routes are generated via the first matching route.
